spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: 271828

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.itheima.pojo
webapi:
  app_id: flrtqfkluhmrycgx
  app_secret: ijaPntiZq5oC6m3QrXEKtWCc96an5iW0

